---
title: "Dashboard showing the most divergent traits"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard) 
library(plotly)
library(tidyverse)
library(htmlwidgets)

```

```{r} 
train <- read.csv("train_imputed.csv")

test <- read.csv("train_imputed.csv")



#### converting the species column to factor ### 

train$Species <- as.factor(train$Species)

test$Species <- as.factor(test$Species)


```


Column {data-width=650}
-----------------------------------------------------------------------

### GENUS

```{r}

################# 3D PLOT BASED ON THE MOST DIVERGENT TRAITS ###### 


library(plotly)

plot <- plot_ly(train,x= ~LTD,y= ~LCirc,z= ~LA, color = ~Species
) %>%
  add_markers() %>%
  layout(
    scene = list(xaxis = list(title = 'LTD'),
                 yaxis = list(title = 'LCirc'),
                 zaxis = list(title = 'LA'))
  )


plot



saveWidget(plot,"Genus3d.html")



```















